// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test1() {
    driver.get("https://leonwesterveld.nl/");
    driver.manage().window().setSize(new Dimension(528, 816));
    driver.findElement(By.id("homepage")).click();
    {
      WebElement element = driver.findElement(By.id("homepage"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("homepage"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("homepage"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("homepage")).click();
    driver.findElement(By.id("button__projects")).click();
    driver.findElement(By.id("button__about")).click();
    driver.findElement(By.id("button__contact")).click();
    driver.findElement(By.id("button__blog")).click();
    driver.findElement(By.id("button__blog")).click();
    driver.findElement(By.cssSelector(".tablinks:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".tablinks:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".tablinks:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".tablinks:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".tablinks:nth-child(1)")).click();
    driver.findElement(By.id("home")).click();
    driver.findElement(By.id("button__about")).click();
    driver.findElement(By.id("home")).click();
    driver.findElement(By.id("darkmode")).click();
    driver.findElement(By.id("darkmode")).click();
    driver.findElement(By.id("taal")).click();
    driver.findElement(By.id("taal")).click();
    driver.findElement(By.id("button__contact")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".hover:nth-child(2) > img")).click();
    vars.put("win2260", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2260").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".hover:nth-child(3) > img")).click();
    vars.put("win599", waitForWindow(2000));
    driver.switchTo().window(vars.get("win599").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".hover:nth-child(4)")).click();
    driver.findElement(By.id("home")).click();
    driver.findElement(By.id("button__blog")).click();
    driver.findElement(By.cssSelector(".fa-regular")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("test");
    driver.findElement(By.id("password")).sendKeys("test");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Stage Blog 1")).click();
    driver.findElement(By.linkText("Blogs")).click();
    driver.findElement(By.linkText("Stage Blog 2")).click();
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("testetetet");
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    driver.findElement(By.id("home")).click();
    driver.findElement(By.id("homepage")).click();
    driver.findElement(By.id("homepage")).click();
  }
}
